In [1]:
import numpy as np


# Creating Numpy Arrays form Python Lists

In [2]:
np.array([1,2,4,522])

array([  1,   2,   4, 522])

In [3]:
[3.14,6,2]

[3.14, 6, 2]

In [4]:
np.array([[3.14,6,2]])

array([[3.14, 6.  , 2.  ]])

In [7]:
# nó giúp mình chuẩn hóa kiểu dữ liệu
np.array([1,324.2,243.2,42], dtype="float32")

array([  1. , 324.2, 243.2,  42. ], dtype=float32)

In [9]:
a1 =np.array([1,2,4,522])

In [11]:
type(a1)

numpy.ndarray

In [14]:
a2=np.array([[3,3,3],[123,24,2]])
type(a2)

numpy.ndarray

In [15]:
a2.shape

(2, 3)

In [17]:
# số chiều của mảng
a2.ndim

2

In [18]:
a2.dtype

dtype('int64')

In [19]:
a2.size

6

# Create Numpy Arrays from Scratch (zeros, one, full, arange, linspace)

In [21]:
np.zeros([2,4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones([2,4], dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.full((2,5),6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### `random`

In [30]:
np.random.random((4,4))

array([[0.01521581, 0.97931127, 0.83951141, 0.85938372],
       [0.39498242, 0.51031414, 0.48171931, 0.86023715],
       [0.92836103, 0.45162163, 0.90384749, 0.31930862],
       [0.60906773, 0.96375885, 0.28600694, 0.92204772]])

In [32]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])